### Employee who leads a node cannot be deleted
# @name DeleteSecondWhileLeader
## TEST-EXPECT-STATUS: [400]
DELETE http://localhost:5080/api/employees/{{EmployeeId}}

### Employee still exists
# @name GetSecondStillExists
## TEST-EXPECT-STATUS: [200]
GET http://localhost:5080/api/employees/{{EmployeeId}}
Accept: application/json
